### login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjdhMjE3ZjZjZGY2YzVhOTU5MDJjNmMiLCJpYXQiOjE2NTIzNDY1NzR9.eHnuJfqEhXgwvcocb-MmKJb5ymjlAPHhdlAiHHZqJm4

POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email": "nisl.elementum@yahoo.com",
    "password": "123456"
}
